name = "formthongtin"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "public"
binding = "ASSETS"

[vars]
BACKGROUND_IMAGE_URL = "https://lh3.googleusercontent.com/d/1Ler6x8p96gZ7T0eeX6oMQofbEWNEgEge"
